import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { getSession } from 'next-auth/react';
import { getAllPosts } from '../lib/posts';
import { connectDB } from '../lib/connectDB';
import MainHeader from '../components/MainNavigation/MainHeader/MainHeader';
import Nav from '../components/MainNavigation/Nav/Nav';
import PostList from '../components/PostList/PostList';
import { RightSideBar } from '../components/RightSideBar/RightSideBar';

export default function Home({ posts, session }) {
  const user = session && session.user;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        {!user && <MainHeader />}
        <div className='container-layout'>
          {user && <Nav user={user} />}
          <PostList posts={posts} />
          <RightSideBar />
        </div>
      </>
    </div>
  );
}

//goal is to tell Next about the data
export async function getServerSideProps(context) {
  const { posts, error } = await getAllPosts();
  const session = await getSession(context);

  if (error) {
    return {
      props: {
        error: error.message,
      },
    };
  }

  return {
    props: {
      posts: JSON.parse(JSON.stringify(posts)),
      session,
    },
  };
}
